title: Ranjodh Singh
author: Ranjodh Singh
description: CSE'27 @NITJ | AI/ML | Open Source | Competitive Programming

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
